import { TimetableSlot, Subject } from './types';

export interface TimetablePreset {
  id: string;
  name: string;
  program: string;
  academicTerm: string;
  department: string;
  description: string;
  subjects: Subject[];
  slots: TimetableSlot[];
}

export const REAL_LIFE_TIMETABLE_PRESETS: TimetablePreset[] = [
  {
    id: 'preset_cse_sem7',
    name: 'B.Tech Computer Science (Sem VII)',
    program: 'B.Tech CSE - 4th Year',
    academicTerm: 'Fall 2026',
    department: 'Computer Science & Engineering',
    description: 'Real-life 8-period engineering timetable with Distributed Cloud, AI & Machine Learning, Compiler Design, and Systems Labs.',
    subjects: [
      {
        id: 'sub_cs701',
        code: 'CS701',
        name: 'Distributed Cloud Systems',
        teacherName: 'Prof. Ananya Sharma',
        periodsPerWeek: 5,
        color: '#13523B',
        roomNumber: 'LH-302',
        credits: 4,
      },
      {
        id: 'sub_cs702',
        code: 'CS702',
        name: 'Deep Learning & Neural Networks',
        teacherName: 'Dr. Vikram Malhotra',
        periodsPerWeek: 5,
        color: '#1E40AF',
        roomNumber: 'LH-301',
        credits: 4,
      },
      {
        id: 'sub_cs703',
        code: 'CS703',
        name: 'Compiler Engineering',
        teacherName: 'Dr. Meenakshi S',
        periodsPerWeek: 4,
        color: '#B45309',
        roomNumber: 'Room 204',
        credits: 3,
      },
      {
        id: 'sub_cs704',
        code: 'CS704',
        name: 'Distributed Security & Cryptography',
        teacherName: 'Dr. Rajesh K',
        periodsPerWeek: 4,
        color: '#047857',
        roomNumber: 'LH-302',
        credits: 3,
      },
      {
        id: 'sub_cs705',
        code: 'CS705',
        name: 'Cloud & AI Research Lab',
        teacherName: 'Prof. Ananya Sharma',
        periodsPerWeek: 4,
        color: '#6D28D9',
        roomNumber: 'Systems Lab 3',
        credits: 2,
      },
      {
        id: 'sub_cs706',
        code: 'CS706',
        name: 'Major Capstone Project Seminar',
        teacherName: 'Prof. Faculty Committee',
        periodsPerWeek: 2,
        color: '#0369A1',
        roomNumber: 'Auditorium 2',
        credits: 2,
      },
    ],
    slots: [
      // Monday
      { day: 'Monday', period: 1, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Distributed Cloud Systems', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Lecture' },
      { day: 'Monday', period: 2, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Deep Learning & Neural Networks', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Lecture' },
      { day: 'Monday', period: 3, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'Compiler Engineering', facultyName: 'Dr. Meenakshi S', room: 'Room 204', type: 'Lecture' },
      { day: 'Monday', period: 4, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Distributed Security & Cryptography', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Lecture' },
      { day: 'Monday', period: 5, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Cloud Systems Tutorial', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Tutorial' },
      { day: 'Monday', period: 6, subjectId: 'sub_cs705', subjectCode: 'CS705', subjectName: 'Cloud & AI Lab', facultyName: 'Prof. Ananya Sharma', room: 'Systems Lab 3', type: 'Lab' },
      { day: 'Monday', period: 7, subjectId: 'sub_cs705', subjectCode: 'CS705', subjectName: 'Cloud & AI Lab', facultyName: 'Prof. Ananya Sharma', room: 'Systems Lab 3', type: 'Lab' },
      { day: 'Monday', period: 8, subjectId: 'sub_cs706', subjectCode: 'CS706', subjectName: 'Major Capstone Project', facultyName: 'Prof. Faculty Committee', room: 'Auditorium 2', type: 'Tutorial' },

      // Tuesday
      { day: 'Tuesday', period: 1, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Deep Learning & Neural Networks', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Lecture' },
      { day: 'Tuesday', period: 2, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Distributed Cloud Systems', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Lecture' },
      { day: 'Tuesday', period: 3, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Distributed Security & Cryptography', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Lecture' },
      { day: 'Tuesday', period: 4, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'Compiler Engineering', facultyName: 'Dr. Meenakshi S', room: 'Room 204', type: 'Lecture' },
      { day: 'Tuesday', period: 5, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Neural Networks Tutorial', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Tutorial' },
      { day: 'Tuesday', period: 6, subjectId: 'sub_cs705', subjectCode: 'CS705', subjectName: 'Cloud & AI Lab', facultyName: 'Prof. Ananya Sharma', room: 'Systems Lab 3', type: 'Lab' },
      { day: 'Tuesday', period: 7, subjectId: 'sub_cs705', subjectCode: 'CS705', subjectName: 'Cloud & AI Lab', facultyName: 'Prof. Ananya Sharma', room: 'Systems Lab 3', type: 'Lab' },
      { day: 'Tuesday', period: 8, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'Compiler Clinic', facultyName: 'Dr. Meenakshi S', room: 'Room 204', type: 'Tutorial' },

      // Wednesday
      { day: 'Wednesday', period: 1, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'Compiler Engineering', facultyName: 'Dr. Meenakshi S', room: 'Room 204', type: 'Lecture' },
      { day: 'Wednesday', period: 2, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Distributed Security & Cryptography', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Lecture' },
      { day: 'Wednesday', period: 3, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Distributed Cloud Systems', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Lecture' },
      { day: 'Wednesday', period: 4, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Deep Learning & Neural Networks', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Lecture' },
      { day: 'Wednesday', period: 5, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Crypto Protocol Analysis', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Tutorial' },
      { day: 'Wednesday', period: 6, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Cloud Architecture Hands-on', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Lecture' },
      { day: 'Wednesday', period: 7, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Deep Learning Seminar', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Tutorial' },
      { day: 'Wednesday', period: 8, subjectId: 'sub_cs706', subjectCode: 'CS706', subjectName: 'Major Capstone Project', facultyName: 'Prof. Faculty Committee', room: 'Auditorium 2', type: 'Tutorial' },

      // Thursday
      { day: 'Thursday', period: 1, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Distributed Cloud Systems', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Lecture' },
      { day: 'Thursday', period: 2, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Deep Learning & Neural Networks', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Lecture' },
      { day: 'Thursday', period: 3, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'Compiler Engineering', facultyName: 'Dr. Meenakshi S', room: 'Room 204', type: 'Lecture' },
      { day: 'Thursday', period: 4, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Distributed Security & Cryptography', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Lecture' },
      { day: 'Thursday', period: 5, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Model Optimization Workshop', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Tutorial' },
      { day: 'Thursday', period: 6, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'AST Parser Lab', facultyName: 'Dr. Meenakshi S', room: 'Lab 2', type: 'Lab' },
      { day: 'Thursday', period: 7, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'AST Parser Lab', facultyName: 'Dr. Meenakshi S', room: 'Lab 2', type: 'Lab' },
      { day: 'Thursday', period: 8, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Zero-Knowledge Workshop', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Tutorial' },

      // Friday
      { day: 'Friday', period: 1, subjectId: 'sub_cs704', subjectCode: 'CS704', subjectName: 'Distributed Security & Cryptography', facultyName: 'Dr. Rajesh K', room: 'LH-302', type: 'Lecture' },
      { day: 'Friday', period: 2, subjectId: 'sub_cs703', subjectCode: 'CS703', subjectName: 'Compiler Engineering', facultyName: 'Dr. Meenakshi S', room: 'Room 204', type: 'Lecture' },
      { day: 'Friday', period: 3, subjectId: 'sub_cs702', subjectCode: 'CS702', subjectName: 'Deep Learning & Neural Networks', facultyName: 'Dr. Vikram Malhotra', room: 'LH-301', type: 'Lecture' },
      { day: 'Friday', period: 4, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Distributed Cloud Systems', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Lecture' },
      { day: 'Friday', period: 5, subjectId: 'sub_cs706', subjectCode: 'CS706', subjectName: 'Capstone Project Evaluation', facultyName: 'Prof. Faculty Committee', room: 'Auditorium 2', type: 'Tutorial' },
      { day: 'Friday', period: 6, subjectId: 'sub_cs705', subjectCode: 'CS705', subjectName: 'Cloud & AI Lab', facultyName: 'Prof. Ananya Sharma', room: 'Systems Lab 3', type: 'Lab' },
      { day: 'Friday', period: 7, subjectId: 'sub_cs705', subjectCode: 'CS705', subjectName: 'Cloud & AI Lab', facultyName: 'Prof. Ananya Sharma', room: 'Systems Lab 3', type: 'Lab' },
      { day: 'Friday', period: 8, subjectId: 'sub_cs701', subjectCode: 'CS701', subjectName: 'Weekly Faculty Review', facultyName: 'Prof. Ananya Sharma', room: 'LH-302', type: 'Tutorial' },
    ],
  },
  {
    id: 'preset_it_devops',
    name: 'B.Tech IT - Cloud & DevOps (Sem VI)',
    program: 'B.Tech IT - 3rd Year',
    academicTerm: 'Spring 2026',
    department: 'Information Technology',
    description: 'Practical DevOps, Full-Stack Web Development, Microservices, and Mobile Computing with dedicated lab blocks.',
    subjects: [
      {
        id: 'sub_it601',
        code: 'IT601',
        name: 'Full Stack Web Architecture',
        teacherName: 'Prof. Sarah Jenkins',
        periodsPerWeek: 5,
        color: '#13523B',
        roomNumber: 'LH-201',
        credits: 4,
      },
      {
        id: 'sub_it602',
        code: 'IT602',
        name: 'DevOps & CI/CD Pipelines',
        teacherName: 'Dr. Arjun Roy',
        periodsPerWeek: 5,
        color: '#0284C7',
        roomNumber: 'LH-202',
        credits: 4,
      },
      {
        id: 'sub_it603',
        code: 'IT603',
        name: 'Mobile App Engineering (iOS/Android)',
        teacherName: 'Prof. Priya Nair',
        periodsPerWeek: 4,
        color: '#B45309',
        roomNumber: 'Lab 5',
        credits: 3,
      },
      {
        id: 'sub_it604',
        code: 'IT604',
        name: 'Database Engineering & NoSQL',
        teacherName: 'Dr. Harish Chandra',
        periodsPerWeek: 4,
        color: '#047857',
        roomNumber: 'LH-201',
        credits: 3,
      },
      {
        id: 'sub_it605',
        code: 'IT605',
        name: 'DevOps & Kubernetes Lab',
        teacherName: 'Dr. Arjun Roy',
        periodsPerWeek: 4,
        color: '#6D28D9',
        roomNumber: 'Cloud Lab 2',
        credits: 2,
      },
    ],
    slots: [
      // Monday
      { day: 'Monday', period: 1, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Full Stack Web Architecture', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Lecture' },
      { day: 'Monday', period: 2, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'DevOps & CI/CD Pipelines', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Lecture' },
      { day: 'Monday', period: 3, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Engineering', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lecture' },
      { day: 'Monday', period: 4, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'Database Engineering & NoSQL', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Lecture' },
      { day: 'Monday', period: 5, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Web Frameworks Tutorial', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Tutorial' },
      { day: 'Monday', period: 6, subjectId: 'sub_it605', subjectCode: 'IT605', subjectName: 'Kubernetes Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Lab' },
      { day: 'Monday', period: 7, subjectId: 'sub_it605', subjectCode: 'IT605', subjectName: 'Kubernetes Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Lab' },
      { day: 'Monday', period: 8, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'Pipeline Troubleshooting', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Tutorial' },

      // Tuesday
      { day: 'Tuesday', period: 1, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'DevOps & CI/CD Pipelines', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Lecture' },
      { day: 'Tuesday', period: 2, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Full Stack Web Architecture', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Lecture' },
      { day: 'Tuesday', period: 3, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'Database Engineering & NoSQL', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Lecture' },
      { day: 'Tuesday', period: 4, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Engineering', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lecture' },
      { day: 'Tuesday', period: 5, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'Container Security', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Tutorial' },
      { day: 'Tuesday', period: 6, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Studio Lab', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lab' },
      { day: 'Tuesday', period: 7, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Studio Lab', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lab' },
      { day: 'Tuesday', period: 8, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'NoSQL Data Modeling', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Tutorial' },

      // Wednesday
      { day: 'Wednesday', period: 1, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Engineering', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lecture' },
      { day: 'Wednesday', period: 2, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'Database Engineering & NoSQL', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Lecture' },
      { day: 'Wednesday', period: 3, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Full Stack Web Architecture', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Lecture' },
      { day: 'Wednesday', period: 4, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'DevOps & CI/CD Pipelines', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Lecture' },
      { day: 'Wednesday', period: 5, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'Database Indexing Clinic', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Tutorial' },
      { day: 'Wednesday', period: 6, subjectId: 'sub_it605', subjectCode: 'IT605', subjectName: 'Kubernetes Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Lab' },
      { day: 'Wednesday', period: 7, subjectId: 'sub_it605', subjectCode: 'IT605', subjectName: 'Kubernetes Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Lab' },
      { day: 'Wednesday', period: 8, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'GraphQL & REST Studio', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Tutorial' },

      // Thursday
      { day: 'Thursday', period: 1, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Full Stack Web Architecture', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Lecture' },
      { day: 'Thursday', period: 2, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'DevOps & CI/CD Pipelines', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Lecture' },
      { day: 'Thursday', period: 3, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Engineering', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lecture' },
      { day: 'Thursday', period: 4, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'Database Engineering & NoSQL', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Lecture' },
      { day: 'Thursday', period: 5, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'State Management Workshop', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Tutorial' },
      { day: 'Thursday', period: 6, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Studio Lab', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lab' },
      { day: 'Thursday', period: 7, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Studio Lab', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lab' },
      { day: 'Thursday', period: 8, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'Terraform IaC Clinic', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Tutorial' },

      // Friday
      { day: 'Friday', period: 1, subjectId: 'sub_it604', subjectCode: 'IT604', subjectName: 'Database Engineering & NoSQL', facultyName: 'Dr. Harish Chandra', room: 'LH-201', type: 'Lecture' },
      { day: 'Friday', period: 2, subjectId: 'sub_it603', subjectCode: 'IT603', subjectName: 'Mobile App Engineering', facultyName: 'Prof. Priya Nair', room: 'Lab 5', type: 'Lecture' },
      { day: 'Friday', period: 3, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'DevOps & CI/CD Pipelines', facultyName: 'Dr. Arjun Roy', room: 'LH-202', type: 'Lecture' },
      { day: 'Friday', period: 4, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Full Stack Web Architecture', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Lecture' },
      { day: 'Friday', period: 5, subjectId: 'sub_it602', subjectCode: 'IT602', subjectName: 'Prometheus & Grafana Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Tutorial' },
      { day: 'Friday', period: 6, subjectId: 'sub_it605', subjectCode: 'IT605', subjectName: 'Kubernetes Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Lab' },
      { day: 'Friday', period: 7, subjectId: 'sub_it605', subjectCode: 'IT605', subjectName: 'Kubernetes Lab', facultyName: 'Dr. Arjun Roy', room: 'Cloud Lab 2', type: 'Lab' },
      { day: 'Friday', period: 8, subjectId: 'sub_it601', subjectCode: 'IT601', subjectName: 'Code Review Session', facultyName: 'Prof. Sarah Jenkins', room: 'LH-201', type: 'Tutorial' },
    ],
  },
  {
    id: 'preset_ece_embedded',
    name: 'B.Tech ECE - Embedded & IoT (Sem VI)',
    program: 'B.Tech ECE - 3rd Year',
    academicTerm: 'Fall 2026',
    department: 'Electronics & Communication Engineering',
    description: 'Embedded Systems, Microcontrollers, Digital Signal Processing, VLSI Design, and IoT Sensor Networks.',
    subjects: [
      {
        id: 'sub_ec601',
        code: 'EC601',
        name: 'Embedded Real-Time Systems',
        teacherName: 'Dr. Sandeep Verma',
        periodsPerWeek: 5,
        color: '#13523B',
        roomNumber: 'LH-104',
        credits: 4,
      },
      {
        id: 'sub_ec602',
        code: 'EC602',
        name: 'Digital Signal Processing (DSP)',
        teacherName: 'Prof. Kavita Rao',
        periodsPerWeek: 5,
        color: '#1E40AF',
        roomNumber: 'LH-105',
        credits: 4,
      },
      {
        id: 'sub_ec603',
        code: 'EC603',
        name: 'VLSI Design & Verilog HDL',
        teacherName: 'Dr. T. Venkataraman',
        periodsPerWeek: 4,
        color: '#B45309',
        roomNumber: 'Room 303',
        credits: 3,
      },
      {
        id: 'sub_ec604',
        code: 'EC604',
        name: 'Wireless Sensor Networks & IoT',
        teacherName: 'Dr. Sandeep Verma',
        periodsPerWeek: 4,
        color: '#047857',
        roomNumber: 'LH-104',
        credits: 3,
      },
      {
        id: 'sub_ec605',
        code: 'EC605',
        name: 'Embedded Systems & DSP Lab',
        teacherName: 'Prof. Kavita Rao',
        periodsPerWeek: 4,
        color: '#6D28D9',
        roomNumber: 'Hardware Lab 1',
        credits: 2,
      },
    ],
    slots: [
      // Monday
      { day: 'Monday', period: 1, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'Embedded Real-Time Systems', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Monday', period: 2, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'Digital Signal Processing', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Lecture' },
      { day: 'Monday', period: 3, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'VLSI Design & Verilog', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Lecture' },
      { day: 'Monday', period: 4, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'Wireless Sensor Networks', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Monday', period: 5, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'RTOS Task Scheduling', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Tutorial' },
      { day: 'Monday', period: 6, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'Embedded Systems Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Monday', period: 7, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'Embedded Systems Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Monday', period: 8, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'MATLAB DSP Tutorial', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Tutorial' },

      // Tuesday
      { day: 'Tuesday', period: 1, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'Digital Signal Processing', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Lecture' },
      { day: 'Tuesday', period: 2, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'Embedded Real-Time Systems', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Tuesday', period: 3, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'Wireless Sensor Networks', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Tuesday', period: 4, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'VLSI Design & Verilog', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Lecture' },
      { day: 'Tuesday', period: 5, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'Filter Design Tutorial', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Tutorial' },
      { day: 'Tuesday', period: 6, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'Embedded Systems Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Tuesday', period: 7, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'Embedded Systems Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Tuesday', period: 8, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'Verilog Simulation Clinic', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Tutorial' },

      // Wednesday
      { day: 'Wednesday', period: 1, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'VLSI Design & Verilog', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Lecture' },
      { day: 'Wednesday', period: 2, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'Wireless Sensor Networks', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Wednesday', period: 3, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'Embedded Real-Time Systems', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Wednesday', period: 4, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'Digital Signal Processing', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Lecture' },
      { day: 'Wednesday', period: 5, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'Zigbee & LoRa Workshop', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Tutorial' },
      { day: 'Wednesday', period: 6, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'ARM Cortex Architecture', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Wednesday', period: 7, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'FFT Algorithms Workshop', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Tutorial' },
      { day: 'Wednesday', period: 8, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'FPGA Synthesis Session', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Tutorial' },

      // Thursday
      { day: 'Thursday', period: 1, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'Embedded Real-Time Systems', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Thursday', period: 2, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'Digital Signal Processing', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Lecture' },
      { day: 'Thursday', period: 3, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'VLSI Design & Verilog', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Lecture' },
      { day: 'Thursday', period: 4, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'Wireless Sensor Networks', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Thursday', period: 5, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'DSP Filter Optimization', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Tutorial' },
      { day: 'Thursday', period: 6, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'DSP Simulation Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Thursday', period: 7, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'DSP Simulation Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Thursday', period: 8, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'IoT Cloud Connectivity', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Tutorial' },

      // Friday
      { day: 'Friday', period: 1, subjectId: 'sub_ec604', subjectCode: 'EC604', subjectName: 'Wireless Sensor Networks', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Friday', period: 2, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'VLSI Design & Verilog', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Lecture' },
      { day: 'Friday', period: 3, subjectId: 'sub_ec602', subjectCode: 'EC602', subjectName: 'Digital Signal Processing', facultyName: 'Prof. Kavita Rao', room: 'LH-105', type: 'Lecture' },
      { day: 'Friday', period: 4, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'Embedded Real-Time Systems', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Lecture' },
      { day: 'Friday', period: 5, subjectId: 'sub_ec603', subjectCode: 'EC603', subjectName: 'VLSI Layout Tutorial', facultyName: 'Dr. T. Venkataraman', room: 'Room 303', type: 'Tutorial' },
      { day: 'Friday', period: 6, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'Embedded Systems Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Friday', period: 7, subjectId: 'sub_ec605', subjectCode: 'EC605', subjectName: 'Embedded Systems Lab', facultyName: 'Prof. Kavita Rao', room: 'Hardware Lab 1', type: 'Lab' },
      { day: 'Friday', period: 8, subjectId: 'sub_ec601', subjectCode: 'EC601', subjectName: 'Weekly Hardware Review', facultyName: 'Dr. Sandeep Verma', room: 'LH-104', type: 'Tutorial' },
    ],
  },
];
